# [mongodb[+srv]://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]
mongodb:
  uri: "mongodb://mongodb:27017"

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
