controller:
  additionalPlugins:
    - cloudbees-disk-usage-simple:178.v1a_4d2f6359a_8
    - blueocean:1.25.8
    - prometheus:2.0.11
  
  prometheus:
    serviceMonitorAdditionalLabels:
      release: prometheus