apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: development
  labels:
    app.kubernetes.i/name: web-frontend
spec:
  type: LoadBalancer
  selector:
      app.kubernetes.i/name: web-frontend
  ports:
    - port: 8080
      name: http
      targetPort: 3000